# dataset infomation
dataset_name: mimic_cxr
image_dir: D:/code/database/mimic_cxr/images/
ann_path: D:/code/database/mimic_cxr/annotation.json
label_path: data/labels/MIMIC/MIMIC_lab.csv

# training parameter
test_steps: 500

# Hyperparameter
#max_seq_length: 100
#num_labels: 14
#threshold: 10 #3
max_seq_length: 80
num_labels: 14
threshold: 3

batch_size: 40
epochs: 30
step_size: 1

num_layers: 3

gamma: 0.8
seed: 9223
lr_ed: 0.0001

label_smoothing: 0.1

# Visual Extractor
# d_vf:
# efficientnet: 1280
# densenet: 1024
# resnet101: 2048
visual_extractor: efficientnet
# pretrain_cnn_file: code/tencent/EfficientNet-PyTorch/archive/runs/efficientnet-b0-normalize0500/model_best.pth.tar
d_vf: 1280

# Output Dir
save_dir: results